name: Dependency Review

on:
  pull_request:
    branches:
      - develop
      - main
      - master
      - workos

permissions:
  contents: read

jobs:
  dependency-review:
    uses: BAGArt/telegram-platform-workflows/.github/workflows/dependency-review.yml@<CENTRAL_SHA> # pin!
