name: Quality

on:
  push:
    branches:
      - develop
      - main
      - master
      - workos
  pull_request:
    branches:
      - develop
      - main
      - master
      - workos

permissions:
  contents: read

jobs:
  quality:
    uses: BAGArt/telegram-platform-workflows/.github/workflows/lint.yml@<CENTRAL_SHA> # pin!
    with:
      php-version: '8.5'
